# Generated by Django 5.2 on 2025-05-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='docs/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
